config/routes.rb
Rails.application.routes.draw do
  resources :enderecos
  resources :municipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :municipe

  validates_presence_of :cep, :address, :complement, :district, :city, :state
end

app/models/municipe.rb
class Municipe < ApplicationRecord
  validates_presence_of :name, :cpf, :cns, :email, :birth_date, :phone, :photo, :status

  validates :my_email_attribute, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: %i[ show edit update destroy ]

  # GET /enderecos or /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1 or /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos or /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully created." }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1 or /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully updated." }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1 or /enderecos/1.json
  def destroy
    @endereco.destroy

    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: "Endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endereco_params
      params.require(:endereco).permit(:cep, :address, :complement, :district, :city, :state, :ibge_cod)
    end
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  require "cpf_cnpj"
  before_action :set_municipe, only: %i[ show edit update destroy ]

  VALIDATE_PARAMS = [
    ['cpf', 'cpf_valid?'],
    ['cns', 'cns_valid?'],
    ['birth_date', 'birth_date_valid?'],
  ].freeze

  # GET /municipes or /municipes.json
  def index
    @municipes = Municipe.all
  end

  # GET /municipes/1 or /municipes/1.json
  def show
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
  end

  # GET /municipes/1/edit
  def edit
  end

  # POST /municipes or /municipes.json
  def create
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe was successfully created." }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe was successfully updated." }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipes/1 or /municipes/1.json
  def destroy
    @municipe.destroy

    respond_to do |format|
      format.html { redirect_to municipes_url, notice: "Municipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipe
      @municipe = Municipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municipe_params
      params.require(:municipe).permit(:name, :cpf, :cns, :email, :birth_date, :phone, :photo, :status)
    end

    def cpf_valid?
      CPF.valid?(params[:cpf]) && !params[:cpf].match?(/[^0-9]/)
    end

    def cns_valid?
      params[:cns].match?(/[^0-9]/)
    end

    def birth_date_valid?
      params[:birth_date].to_date
      params[:birth_date].match?(/[0-9]{2}-[0-9]{2}-[0-9]{4}/) && params[:birth_date].length == 10
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/views/enderecos/_form.html.erb
<%= form_with(model: endereco, local: true) do |form| %>
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :complement %>
    <%= form.text_field :complement %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :ibge_cod %>
    <%= form.text_field :ibge_cod %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Cep</th>
      <th>Address</th>
      <th>Complement</th>
      <th>District</th>
      <th>City</th>
      <th>State</th>
      <th>Ibge cod</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.cep %></td>
        <td><%= endereco.address %></td>
        <td><%= endereco.complement %></td>
        <td><%= endereco.district %></td>
        <td><%= endereco.city %></td>
        <td><%= endereco.state %></td>
        <td><%= endereco.ibge_cod %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>New Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Back', enderecos_path %>

app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cep:</strong>
  <%= @endereco.cep %>
</p>

<p>
  <strong>Address:</strong>
  <%= @endereco.address %>
</p>

<p>
  <strong>Complement:</strong>
  <%= @endereco.complement %>
</p>

<p>
  <strong>District:</strong>
  <%= @endereco.district %>
</p>

<p>
  <strong>City:</strong>
  <%= @endereco.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @endereco.state %>
</p>

<p>
  <strong>Ibge cod:</strong>
  <%= @endereco.ibge_cod %>
</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jedis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/municipes/_form.html.erb
<%= form_with(model: municipe, local: true) do |form| %>
  <% if municipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(municipe.errors.count, "error") %> prohibited this municipe from being saved:</h2>

      <ul>
      <% municipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :cns %>
    <%= form.number_field :cns %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/municipes/edit.html.erb
<h1>Editing Municipe</h1>

<%= render 'form', municipe: @municipe %>

<%= link_to 'Show', @municipe %> |
<%= link_to 'Back', municipes_path %>

app/views/municipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Municipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Cns</th>
      <th>Email</th>
      <th>Birth date</th>
      <th>Phone</th>
      <th>Photo</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipes.each do |municipe| %>
      <tr>
        <td><%= municipe.name %></td>
        <td><%= municipe.cpf %></td>
        <td><%= municipe.cns %></td>
        <td><%= municipe.email %></td>
        <td><%= municipe.birth_date %></td>
        <td><%= municipe.phone %></td>
        <td><%= municipe.photo %></td>
        <td><%= municipe.status %></td>
        <td><%= link_to 'Show', municipe %></td>
        <td><%= link_to 'Edit', edit_municipe_path(municipe) %></td>
        <td><%= link_to 'Destroy', municipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Municipe', new_municipe_path %>

app/views/municipes/new.html.erb
<h1>New Municipe</h1>

<%= render 'form', municipe: @municipe %>

<%= link_to 'Back', municipes_path %>

app/views/municipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @municipe.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @municipe.cpf %>
</p>

<p>
  <strong>Cns:</strong>
  <%= @municipe.cns %>
</p>

<p>
  <strong>Email:</strong>
  <%= @municipe.email %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @municipe.birth_date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @municipe.phone %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @municipe.photo %>
</p>

<p>
  <strong>Status:</strong>
  <%= @municipe.status %>
</p>

<%= link_to 'Edit', edit_municipe_path(@municipe) %> |
<%= link_to 'Back', municipes_path %>